FROM node:12.13-alpine As development

RUN apk add git openssh-client
WORKDIR /usr/src/app

COPY . .

RUN yarn run install
RUN yarn run build

EXPOSE 8080
CMD [ "npm", "start" ]

FROM node:12.13-alpine as production
WORKDIR /usr/src/app

COPY package*.json ./
COPY --from=development /usr/src/app/node_modules ./usr/src/app/node_modules
COPY --from=development /usr/src/app/dist ./usr/src/app/dist

EXPOSE 8080
CMD ["node", "dist/main"]
