version: "3.7"
services:
  soda:
    container_name: reisetra-soda
    image: "reisetra-soda:dev"
    build:
      context: ./
      target: development
    volumes:
      - "./src:/usr/src/app/src"
    ports:
      - "8080:8080"
    working_dir: "/usr/src/app"
    command:
      - node dist/main.js
    networks:
      - soda-backend
    depends_on:
      - redis-global
      - postgres-global
    env_file: .env
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "localhost:8080/api/v1/healthz -q -O - > /dev/null 2>&1",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    # restart: "on-failure"
  redis-global:
    container_name: reisetra-soda-redis
    image: redis:latest
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - soda-backend
    env_file: .env
    volumes:
      - ./databases/redis:/data
    restart: always

  postgres-global:
    container_name: reisetra-soda-postgres
    image: postgres:latest
    restart: always
    env_file: .env
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./databases/postgres:/var/lib/postgresql
    networks:
      - soda-backend

networks:
  soda-backend:
