module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  modulePaths: ['<rootDir>'],
  testEnvironment: 'node',
  testRegex: '.e2e-spec.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  setupFiles: ['dotenv/config'],
  roots: ['<rootDir>/src/', '<rootDir>/libs/'],
  moduleNameMapper: {
    '@app/core/(.*)': '<rootDir>/libs/core/src/$1',
    '@app/core': '<rootDir>/libs/core/src',
    '@app/utils/(.*)': '<rootDir>/libs/utils/src/$1',
    '@app/utils': '<rootDir>/libs/utils/src',
    '@app/aws/(.*)': '<rootDir>/libs/aws/src/$1',
    '@app/aws': '<rootDir>/libs/aws/src',
    '@app/config/(.*)': '<rootDir>/libs/config/src/$1',
    '@app/config': '<rootDir>/libs/config/src',
    '@app/cache/(.*)': '<rootDir>/libs/cache/src/$1',
    '@app/cache': '<rootDir>/libs/cache/src',
    '@app/db/(.*)': '<rootDir>/libs/db/src/$1',
    '@app/db': '<rootDir>/libs/db/src',
    '@app/health/(.*)': '<rootDir>/libs/health/src/$1',
    '@app/health': '<rootDir>/libs/health/src',
    '@app/auth/(.*)': '<rootDir>/libs/auth/src/$1',
    '@app/auth': '<rootDir>/libs/auth/src',
    '@app/user/(.*)': '<rootDir>/libs/user/src/$1',
    '@app/user': '<rootDir>/libs/user/src',
    '@app/notification/(.*)': '<rootDir>/libs/notification/src/$1',
    '@app/notification': '<rootDir>/libs/notification/src',
    '@app/master/(.*)': '<rootDir>/libs/master/src/$1',
    '@app/master': '<rootDir>/libs/master/src',
  },
}
